package fr.cybercicco.artifacts;

public enum SyntaxKind {
    NUMBER_TOKEN,
    WHITESPACE_TOKEN,
    PLUS_TOKEN,
    MINUS_TOKEN,
    MULT_TOKEN,
    DIV_TOKEN,
    MODULO_TOKEN,
    OPENPARENTHESIS_TOKEN,
    CLOSEPARENTHESIS_TOKEN,
    BAD_TOKEN,
    ENDOFFILE_TOKEN,
    NUMBER_EXPRESSION,
    BINARY_EXPRESSION,
}